import {
  Monitor,
  Video,
  Camera,
  Tv,
  Projector,
  Router,
  Network,
  Wifi,
  Server,
  Box,
  Cpu,
  HardDrive,
  Speaker,
  Mic,
  Headphones,
  Music,
  Volume2,
  Radio,
  TabletSmartphone,
  Gamepad2,
  SlidersHorizontal,
  Cable,
  Plug,
  PlugZap,
  Circle,
  Type,
  PanelTop,
  Spline,
  Disc,
  Usb,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface NodeTypeConfig {
  type: string
  label: string
  category: string
  icon: LucideIcon
  description?: string
}

export const nodeTypes: NodeTypeConfig[] = [
  {
    type: 'videoSource',
    label: 'Video Source',
    category: 'Video',
    icon: Video,
    description: 'Generic video source input',
  },
  {
    type: 'camera',
    label: 'Camera',
    category: 'Video',
    icon: Camera,
    description: 'PTZ or fixed camera',
  },
  {
    type: 'mediaPlayer',
    label: 'Media Player',
    category: 'Video',
    icon: Disc,
    description: 'Video playback device',
  },
  {
    type: 'laptop',
    label: 'Laptop/PC',
    category: 'Video',
    icon: Monitor,
    description: 'Computer video source',
  },
  {
    type: 'display',
    label: 'Display',
    category: 'Video',
    icon: Monitor,
    description: 'Monitor or screen',
  },
  {
    type: 'projector',
    label: 'Projector',
    category: 'Video',
    icon: Projector,
    description: 'Video projector',
  },
  {
    type: 'ledWall',
    label: 'LED Wall',
    category: 'Video',
    icon: Tv,
    description: 'LED video wall',
  },
  {
    type: 'videoSwitcher',
    label: 'Video Switcher',
    category: 'Video',
    icon: Spline,
    description: 'Matrix or presentation switcher',
  },
  {
    type: 'scaler',
    label: 'Scaler',
    category: 'Video',
    icon: SlidersHorizontal,
    description: 'Video scaler/processor',
  },
  {
    type: 'encoder',
    label: 'Encoder',
    category: 'Video',
    icon: HardDrive,
    description: 'Video encoder/streaming',
  },
  {
    type: 'decoder',
    label: 'Decoder',
    category: 'Video',
    icon: Box,
    description: 'Video decoder',
  },
  {
    type: 'audioSource',
    label: 'Audio Source',
    category: 'Audio',
    icon: Music,
    description: 'Generic audio source',
  },
  {
    type: 'microphone',
    label: 'Microphone',
    category: 'Audio',
    icon: Mic,
    description: 'Microphone input',
  },
  {
    type: 'wirelessMic',
    label: 'Wireless Mic',
    category: 'Audio',
    icon: Radio,
    description: 'Wireless microphone system',
  },
  {
    type: 'speaker',
    label: 'Speaker',
    category: 'Audio',
    icon: Speaker,
    description: 'Loudspeaker',
  },
  {
    type: 'headphones',
    label: 'Headphones',
    category: 'Audio',
    icon: Headphones,
    description: 'Headphone output',
  },
  {
    type: 'dsp',
    label: 'DSP',
    category: 'Audio',
    icon: Cpu,
    description: 'Digital signal processor',
  },
  {
    type: 'audioMixer',
    label: 'Audio Mixer',
    category: 'Audio',
    icon: SlidersHorizontal,
    description: 'Audio mixing console',
  },
  {
    type: 'amplifier',
    label: 'Amplifier',
    category: 'Audio',
    icon: Volume2,
    description: 'Power amplifier',
  },
  {
    type: 'controller',
    label: 'Controller',
    category: 'Control',
    icon: Cpu,
    description: 'Control processor',
  },
  {
    type: 'touchPanel',
    label: 'Touch Panel',
    category: 'Control',
    icon: TabletSmartphone,
    description: 'Touch control panel',
  },
  {
    type: 'controlSystem',
    label: 'Control System',
    category: 'Control',
    icon: Gamepad2,
    description: 'Central control system',
  },
  {
    type: 'networkSwitch',
    label: 'Network Switch',
    category: 'Network',
    icon: Network,
    description: 'Ethernet switch',
  },
  {
    type: 'router',
    label: 'Router',
    category: 'Network',
    icon: Router,
    description: 'Network router',
  },
  {
    type: 'wifi',
    label: 'WiFi AP',
    category: 'Network',
    icon: Wifi,
    description: 'Wireless access point',
  },
  {
    type: 'server',
    label: 'Server',
    category: 'Network',
    icon: Server,
    description: 'Server or NVR',
  },
  {
    type: 'input',
    label: 'Input',
    category: 'Generic',
    icon: Plug,
    description: 'Signal input port',
  },
  {
    type: 'output',
    label: 'Output',
    category: 'Generic',
    icon: PlugZap,
    description: 'Signal output port',
  },
  {
    type: 'label',
    label: 'Label',
    category: 'Generic',
    icon: Type,
    description: 'Text annotation',
  },
  {
    type: 'note',
    label: 'Note',
    category: 'Generic',
    icon: Circle,
    description: 'Sticky note',
  },
  {
    type: 'cable',
    label: 'Cable',
    category: 'Generic',
    icon: Cable,
    description: 'Cable or connection',
  },
  {
    type: 'usb',
    label: 'USB',
    category: 'Generic',
    icon: Usb,
    description: 'USB device or hub',
  },
  {
    type: 'rack',
    label: 'Rack',
    category: 'Generic',
    icon: PanelTop,
    description: 'Equipment rack',
  },
]

export type NodeType = typeof nodeTypes[number]['type']

export const nodeCategories = ['Video', 'Audio', 'Control', 'Network', 'Generic'] as const

export function getNodeTypeConfig(type: string): NodeTypeConfig | undefined {
  return nodeTypes.find((n) => n.type === type)
}

export const nodeColors: Record<string, { border: string; bg: string }> = {
  videoSource: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  camera: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  mediaPlayer: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  laptop: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  display: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  projector: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  ledWall: { border: 'border-blue-500', bg: 'bg-blue-500/10' },
  videoSwitcher: { border: 'border-blue-400', bg: 'bg-blue-400/10' },
  scaler: { border: 'border-blue-300', bg: 'bg-blue-300/10' },
  encoder: { border: 'border-blue-300', bg: 'bg-blue-300/10' },
  decoder: { border: 'border-blue-300', bg: 'bg-blue-300/10' },
  audioSource: { border: 'border-green-500', bg: 'bg-green-500/10' },
  microphone: { border: 'border-green-500', bg: 'bg-green-500/10' },
  wirelessMic: { border: 'border-green-500', bg: 'bg-green-500/10' },
  speaker: { border: 'border-green-500', bg: 'bg-green-500/10' },
  headphones: { border: 'border-green-500', bg: 'bg-green-500/10' },
  dsp: { border: 'border-green-400', bg: 'bg-green-400/10' },
  audioMixer: { border: 'border-green-400', bg: 'bg-green-400/10' },
  amplifier: { border: 'border-green-300', bg: 'bg-green-300/10' },
  controller: { border: 'border-purple-500', bg: 'bg-purple-500/10' },
  touchPanel: { border: 'border-purple-400', bg: 'bg-purple-400/10' },
  controlSystem: { border: 'border-purple-500', bg: 'bg-purple-500/10' },
  networkSwitch: { border: 'border-orange-500', bg: 'bg-orange-500/10' },
  router: { border: 'border-orange-500', bg: 'bg-orange-500/10' },
  wifi: { border: 'border-orange-400', bg: 'bg-orange-400/10' },
  server: { border: 'border-orange-400', bg: 'bg-orange-400/10' },
  input: { border: 'border-gray-500', bg: 'bg-gray-500/10' },
  output: { border: 'border-gray-500', bg: 'bg-gray-500/10' },
  label: { border: 'border-gray-400', bg: 'bg-gray-400/10' },
  note: { border: 'border-yellow-400', bg: 'bg-yellow-400/10' },
  cable: { border: 'border-gray-400', bg: 'bg-gray-400/10' },
  usb: { border: 'border-gray-400', bg: 'bg-gray-400/10' },
  rack: { border: 'border-gray-500', bg: 'bg-gray-500/10' },
}
